### ISSUE TITLE
[Feature Request] Add docker image

### ISSUE THREAD

**Issue by CygnusHyoga** [xdpirate/gamehorizon#1]
It would be nice to add the pre build docker image to the github or dockerhub registry with semver (semantic versioning). Thanks!

**Comment by xdpirate** [comment]
I have no plans to provide a docker image for now. There is a docker-compose.yml provided if you want to run with docker. [Instructions in the readme](https://github.com/xdpirate/gamehorizon?tab=readme-ov-file#running-with-docker).
